spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sys_security?characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: abc123
  redis:
    host: 116.63.188.39
    port: 6379
    password: '@KunKun2023'
    database: 0
server:
  port: 8888